"""crete_db

Revision ID: 024f8a5fcef3
Revises: 
Create Date: 2026-02-22 11:41:03.605321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '024f8a5fcef3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('entrepreneur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrepreneur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', 'entrepreneur_id', name='uq_name_address_entrepreneur_id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(length=1200), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('entrepreneur_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrepreneur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'entrepreneur_id', 'user_id', 'date', name='uq_appointment_service_entrepreneur_user_date')
    )
    op.drop_index(op.f('ix_vending_machines_location'), table_name='vending_machines')
    op.drop_table('vending_machines')
    op.drop_table('tovary')
    op.drop_table('sales')
    op.drop_table('products')
    op.drop_table('service')
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('telegram_linked_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('is_entrepreneur', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('users', 'is_entrepreneur')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'username')
    op.drop_column('users', 'telegram_linked_at')
    op.drop_column('users', 'telegram_id')
    op.create_table('service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('problems', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('executor', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['vending_machines.id'], name=op.f('service_machine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_pkey'))
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('avalible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('min_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sales_propensity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('product_name', name='products_product_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale_sum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['vending_machines.id'], name=op.f('sales_machine_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('sales_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_pkey'))
    )
    op.create_table('tovary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('existing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_zapas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sellings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tovary_pkey'))
    )
    op.create_table('vending_machines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_income', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('inventory_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_of_manufacture', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('commissioning_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_verification', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('verification_interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ta_resource', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_repair', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vending_machines_pkey')),
    sa.UniqueConstraint('inventory_number', name=op.f('vending_machines_inventory_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('serial_number', name=op.f('vending_machines_serial_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_vending_machines_location'), 'vending_machines', ['location'], unique=False)
    op.drop_table('appointments')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    op.drop_table('magic_tokens')
    # ### end Alembic commands ###
