"""initial_schema

Revision ID: 98a1f2f343db
Revises: 
Create Date: 2026-06-02 19:57:53.509309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a1f2f343db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('telegram_linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_entrepreneur', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'moderator', name='user_role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=150), nullable=False, comment='Причина бана'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя, который получил бан'),
    sa.Column('banned_by', sa.Integer(), nullable=False, comment='Тот, кто выдал бан'),
    sa.Column('revoked_by', sa.Integer(), nullable=True, comment='Тот, кто снял бан'),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Время окончания бана'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Время отмены бана'),
    sa.Column('revoked_reason', sa.String(length=150), nullable=True, comment='Причина отмены бана'),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > banned_at', name='ck_ban_expires_after_banned'),
    sa.CheckConstraint('revoked_at IS NULL OR (revoked_at >= banned_at AND (expires_at IS NULL OR revoked_at <= expires_at))', name='ck_ban_revoke_logic'),
    sa.ForeignKeyConstraint(['banned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bans_banned_by'), 'bans', ['banned_by'], unique=False)
    op.create_index(op.f('ix_bans_revoked_by'), 'bans', ['revoked_by'], unique=False)
    op.create_index(op.f('ix_bans_user_id'), 'bans', ['user_id'], unique=False)
    op.create_index('uq_active_ban', 'bans', ['user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('magic_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('entrepreneur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrepreneur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', 'entrepreneur_id', name='uq_name_address_entrepreneur_id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(length=1200), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('entrepreneur_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrepreneur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'entrepreneur_id', 'user_id', 'date', name='uq_appointment_service_entrepreneur_user_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    op.drop_table('magic_tokens')
    op.drop_index('uq_active_ban', table_name='bans', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_bans_user_id'), table_name='bans')
    op.drop_index(op.f('ix_bans_revoked_by'), table_name='bans')
    op.drop_index(op.f('ix_bans_banned_by'), table_name='bans')
    op.drop_table('bans')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
