- id: deploy # станет частью url hooks/deploy
  execute-command: /home/fl1rix/SteelTime/deploy/deploy.sh
  command-working-directory: /home/fl1rix/SteelTime
  trigger-rule:
    match:
      type: payload-hmac-sha256
      secret: "ЗАМЕНИТЬ НА РЕАЛЬНЫЙ"
      parameter:
        source: header
        name: X-Hub-Signature-256


# генерацию ключа openssl rand -hex 32
# путь для конфига /etc/webhook.conf
